<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lesaja</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/responsive.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light fixed-top">
    <a class="navbar-brand" href="#"><img src="img/lesaja.png" alt="Logo" style="width: 100px;"> Tentor</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="#">Kelas Saya</a>
        </li>
    </ul>
    <ul class="navbar-nav">
        <li class="nav-item">
        <a class="btn btn-outline-success" href="#">DAFTAR</a>
        </li>
        <li class="nav-item">
        <a class="btn btn-success ml-md-2" href="#">MASUK</a>
        </li>
    </ul>
    </nav>
</body>
</html>