<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lesaja</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/responsive.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="full">
    <header class="headerapi">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <!-- Brand -->
            <a class="navbar-brand"><img src="img/lesaja.png" width=100></a>

            <!-- Links -->
            <div class="collapse navbar-collapse">
                <div class="indexbtn1" align="right">
                    <div class="btnregis" align="center">
                        <a href="/register" class="btn btn-dash-outline" type="button">DAFTAR</a>
                    </div>
                    <div class="btnmasuk" align="center">
                        <a href="/login" class="btn btn-dash" href="/login" type="button">MASUK</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>

<!-- content -->
    <div class="mainn">
        <div class="box-kelas">
            <div class="cover-mapel1">
                <div class="mapel-judul" align="left">
                    <br><br><br>
                    <img src="img/course.png" width=60px>
                    <br><br>
                    <label class="judul" for="judul">Jenjang</label><br>
                    <label class="judul" for="judul">SD</label><br>
                    <br>
                    <label for="other">Lihat lainnya</label>
                    <a href="/login" class="btn btn-link-other">
                        <img src="img/arrow.png" width=12px>
                    </a>
                </div>
                <div class="mapel-list">
                    <div class="mapel-1" align="center">
                        <div class="icon-mapel bi">
                            <br><br>
                            <img src="img/indonesia.png" width=60px>
                        </div>
                        <div class="content-mapel" align="center">
                            <br>
                            <label for="indonesia">Bahasa Indonesia</label>
                            <a href="/login" class="btn btn-primary:hover btn-join">
                                Join Kelas
                            </a>
                        </div>
                    </div>
                    <div class="mapel-2" align="center">
                        <div class="icon-mapel tik">
                            <br><br>
                            <img src="img/tik.png" width=80px>
                        </div>
                        <div class="content-mapel" align="center">
                            <br>
                            <label for="tik">TIK</label><br>
                            <a href="/login" class="btn btn-primary:hover btn-join">
                                Join Kelas
                            </a>
                        </div>
                    </div>
                    <div class="mapel-3" align="center">
                        <div class="icon-mapel ips">
                            <br><br>
                            <img src="img/social.png" width=80px>
                        </div>
                        <div class="content-mapel" align="center">
                            <br>
                            <label for="math">Ilmu Pengetahuan Sosial</label>
                            <a href="/login" class="btn btn-primary:hover btn-join">
                                Join Kelas
                            </a>
                        </div>
                    </div>
                    <div class="mapel-4" align="center">
                        <div class="icon-mapel inggris">
                            <br><br>
                            <img src="img/inggris.png" width=60px>
                        </div>
                        <div class="content-mapel" align="center">
                            <br>
                            <label>Bahasa Inggris</label>
                            <a href="/login" class="btn btn-primary:hover btn-join">
                                Join Kelas
                            </a>
                        </div>
                    </div>
                    <div class="mapel-5" align="center">
                        <div class="icon-mapel ipa">
                            <br><br>
                            <img src="img/ipa.png" width=80px>
                        </div>
                        <div class="content-mapel" align="center">
                            <br>
                            <label>Ilmu Pengetahuan Alam</label>
                            <a href="/login" class="btn btn-primary:hover btn-join">
                                Join Kelas
                            </a>
                        </div>
                    </div>
                    <div class="mapel-6" align="center">
                        <div class="icon-mapel mat">
                            <br><br>
                            <img src="img/matematika.png" width=80px>
                        </div>
                        <div class="content-mapel" align="center">
                            <br>
                            <label for="math">Matematika</label>
                            <a href="/login" class="btn btn-primary:hover btn-join">
                                Join Kelas
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-kelas box-2">
            <div class="cover-mapel">
                <div class="mapel-judul" align="left">
                    <br><br><br>
                    <img src="img/course.png" width=60px>
                    <br><br>
                    <label class="judul" for="judul">Jenjang</label><br>
                    <label class="judul" for="judul">SMP</label><br>
                    <br>
                    <label for="other">Lihat lainnya</label>
                    <a href="/login" class="btn btn-link-other">
                        <img src="img/arrow.png" width=12px>
                    </a>
                </div>
                <div class="mapel-1">
                    <div class="icon-mapel fisika" align="center">
                        <br><br>
                        <img src="img/fisika.png" width=80px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="fisika">Fisika</label>
                        <br>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-2">
                    <div class="icon-mapel ipa" align="center">
                        <br><br>
                        <img src="img/ipa.png" width=80px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="kimia">Kimia</label>
                        <br>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-3">
                    <div class="icon-mapel biologi" align="center">
                        <br><br>
                        <img src="img/biologi.png" width=80px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="math">Biologi</label>
                        <br>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-4" align="center">
                    <div class="icon-mapel bi">
                        <br><br>
                        <img src="img/indonesia.png" width=60px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="indonesia">Bahasa Indonesia</label>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-5" align="center">
                    <div class="icon-mapel mat">
                        <br><br>
                        <img src="img/matematika.png" width=80px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="indonesia">Matematika</label>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-6" align="center">
                    <div class="icon-mapel inggris">
                        <br><br>
                        <img src="img/inggris.png" width=60px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="indonesia">Bahasa Indonesia</label>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-kelas box-3">
            <div class="cover-mapel">
                <div class="mapel-judul" align="left">
                    <br><br><br>
                    <img src="img/course.png" width=60px>
                    <br><br>
                    <label class="judul" for="judul">Jenjang</label><br>
                    <label class="judul" for="judul">SMA</label><br>
                    <br>
                    <label for="other">Lihat lainnya</label>
                    <a href="/login" class="btn btn-link-other">
                        <img src="img/arrow.png" width=12px>
                    </a>
                </div>
                <div class="mapel-1">
                    <div class="icon-mapel mat" align="center">
                        <br><br>
                        <img src="img/matematika.png" width=80px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="math">Matematika</label>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-2">
                    <div class="icon-mapel fisika" align="center">
                        <br><br>
                        <img src="img/fisika.png" width=80px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="fisika">Fisika</label><br>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-3">
                    <div class="icon-mapel inggris" align="center">
                        <br><br>
                        <img src="img/inggris.png" width=60px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="english">Bahasa Inggris</label><br>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-4">
                    <div class="icon-mapel ipa" align="center">
                        <br><br>
                        <img src="img/ipa.png" width=80px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="kimia">Kimia</label>
                        <br>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-5">
                    <div class="icon-mapel biologi" align="center">
                        <br><br>
                        <img src="img/biologi.png" width=80px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label>Biologi</label>
                        <br>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
                <div class="mapel-6">
                    <div class="icon-mapel bi" align="center">
                        <br><br>
                        <img src="img/indonesia.png" width=60px>
                    </div>
                    <div class="content-mapel" align="center">
                        <br>
                        <label for="english">Bahasa Indonesia</label><br>
                        <a href="/login" class="btn btn-primary:hover btn-join">
                            Join Kelas
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>